### ISSUE TITLE
Python DHT Beispiel lässt sich nicht ausführen

### ISSUE THREAD

**Issue by mstroh76** [mstroh76/Raspjamming#28]
° Zeichen wird nicht unterstützt
![grafik](https://user-images.githubusercontent.com/10127355/37933696-496d18ec-314c-11e8-9f5b-27db6ce0a387.png)
* Falscher Pin, richtig ist 4
* Fehler 'DHT 22 is not defined'

**Comment by woergi** [comment]
Pkt. 1) Behoben in d77198bd22a534ac3f6daa39a42bd7341ae4f98c
 # -*- coding: utf-8 -*

**Comment by mstroh76** [comment]
LaTex kann kein UTF8. Im LaTex Source bitte keine UTF8 kodierte Zeichen verwenden

**Comment by mstroh76** [comment]
Bitte am wip arbeiten, hab Pkt 2 & UTF8 Problem behoben
Pkt 3  noch offen.
